/*
 Navicat Premium Data Transfer

 Source Server         : Oracle
 Source Server Type    : Oracle
 Source Server Version : 110200
 Source Host           : localhost:1521
 Source Schema         : SCOTT

 Target Server Type    : Oracle
 Target Server Version : 110200
 File Encoding         : 65001

 Date: 15/05/2019 19:29:12
*/


-- ----------------------------
-- Table structure for PWD_LOG
-- ----------------------------
DROP TABLE "SCOTT"."PWD_LOG";
CREATE TABLE "SCOTT"."PWD_LOG" (
  "ID" NUMBER NOT NULL ,
  "USERID" NUMBER ,
  "URL" VARCHAR2(64 BYTE) NOT NULL ,
  "IP" VARCHAR2(64 BYTE) NOT NULL ,
  "UA" VARCHAR2(255 BYTE) NOT NULL ,
  "JSON" VARCHAR2(4000 BYTE) NOT NULL ,
  "TIME" VARCHAR2(64 BYTE) NOT NULL ,
  "RECORD" VARCHAR2(64 BYTE) 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for PWD_NOTEPAD
-- ----------------------------
DROP TABLE "SCOTT"."PWD_NOTEPAD";
CREATE TABLE "SCOTT"."PWD_NOTEPAD" (
  "ID" NUMBER NOT NULL ,
  "USERID" NUMBER NOT NULL ,
  "TITLE" VARCHAR2(64 BYTE) NOT NULL ,
  "CONTENT" VARCHAR2(64 BYTE) NOT NULL ,
  "STIME" VARCHAR2(64 BYTE) NOT NULL ,
  "TYPE" NUMBER NOT NULL 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for PWD_NOTICE
-- ----------------------------
DROP TABLE "SCOTT"."PWD_NOTICE";
CREATE TABLE "SCOTT"."PWD_NOTICE" (
  "ID" NUMBER NOT NULL ,
  "CONTENT" VARCHAR2(64 BYTE) ,
  "TIME" VARCHAR2(64 BYTE) ,
  "GRADE" NUMBER 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for PWD_PLAN
-- ----------------------------
DROP TABLE "SCOTT"."PWD_PLAN";
CREATE TABLE "SCOTT"."PWD_PLAN" (
  "ID" NUMBER NOT NULL ,
  "USERID" NUMBER ,
  "USERNAME" VARCHAR2(64 BYTE) ,
  "EMAIL" VARCHAR2(64 BYTE) ,
  "STIME" VARCHAR2(64 BYTE) ,
  "TYPE" NUMBER ,
  "CONTENT" VARCHAR2(500 BYTE) ,
  "STATUS" NUMBER 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for PWD_PWD
-- ----------------------------
DROP TABLE "SCOTT"."PWD_PWD";
CREATE TABLE "SCOTT"."PWD_PWD" (
  "ID" NUMBER NOT NULL ,
  "USERID" NUMBER NOT NULL ,
  "TITLE" VARCHAR2(64 BYTE) ,
  "DESCR" VARCHAR2(64 BYTE) ,
  "USERNAME" VARCHAR2(64 BYTE) NOT NULL ,
  "PASS" VARCHAR2(255 BYTE) NOT NULL ,
  "WEBURL" VARCHAR2(64 BYTE) ,
  "INTIME" VARCHAR2(64 BYTE) ,
  "LASTTIME" VARCHAR2(64 BYTE) NOT NULL ,
  "TPASS" VARCHAR2(64 BYTE) NOT NULL ,
  "STATUS" NUMBER NOT NULL ,
  "TYPE" NUMBER NOT NULL 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for PWD_SET
-- ----------------------------
DROP TABLE "SCOTT"."PWD_SET";
CREATE TABLE "SCOTT"."PWD_SET" (
  "ID" NUMBER NOT NULL ,
  "USERNAME" VARCHAR2(64 BYTE) NOT NULL ,
  "PASS" VARCHAR2(64 BYTE) NOT NULL ,
  "QQ" NUMBER NOT NULL ,
  "EMAIL" VARCHAR2(64 BYTE) NOT NULL ,
  "TITLE" VARCHAR2(64 BYTE) ,
  "DESCRIBE" VARCHAR2(64 BYTE) ,
  "KEYWORDS" VARCHAR2(64 BYTE) ,
  "SIGN" NUMBER NOT NULL ,
  "EMAIL_SIGN" NUMBER ,
  "IPADMIN" VARCHAR2(64 BYTE) 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of PWD_SET
-- ----------------------------
INSERT INTO "SCOTT"."PWD_SET" VALUES ('1', 'zhangwentian', '6a4bcd2e92a2e1ee7108f86f7ee481db', '862163687', '862163687@qq.com', '标题', '描述', '关键词1', '1', '1', ' ');

-- ----------------------------
-- Table structure for PWD_SMTP
-- ----------------------------
DROP TABLE "SCOTT"."PWD_SMTP";
CREATE TABLE "SCOTT"."PWD_SMTP" (
  "ID" NUMBER NOT NULL ,
  "HOST" VARCHAR2(64 BYTE) NOT NULL ,
  "PORT" NUMBER NOT NULL ,
  "USERNAME" VARCHAR2(64 BYTE) NOT NULL ,
  "PASSWORD" VARCHAR2(64 BYTE) NOT NULL ,
  "SUB" VARCHAR2(64 BYTE) NOT NULL ,
  "SSL" NUMBER NOT NULL 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of PWD_SMTP
-- ----------------------------
INSERT INTO "SCOTT"."PWD_SMTP" VALUES ('1', 'smtp.exmail.qq.com', '465', ' ', ' ', 'Zzz', '1');

-- ----------------------------
-- Table structure for PWD_USER
-- ----------------------------
DROP TABLE "SCOTT"."PWD_USER";
CREATE TABLE "SCOTT"."PWD_USER" (
  "ID" NUMBER NOT NULL ,
  "USERNAME" VARCHAR2(64 BYTE) NOT NULL ,
  "PASS" VARCHAR2(64 BYTE) NOT NULL ,
  "EMAIL" VARCHAR2(64 BYTE) NOT NULL ,
  "QQ" NUMBER ,
  "STIME" VARCHAR2(64 BYTE) ,
  "LTIME" VARCHAR2(64 BYTE) NOT NULL ,
  "SIP" VARCHAR2(64 BYTE) ,
  "LIP" VARCHAR2(64 BYTE) NOT NULL ,
  "TOKEN" VARCHAR2(64 BYTE) NOT NULL ,
  "STATUS" NUMBER NOT NULL ,
  "ERROR_NUM" NUMBER NOT NULL ,
  "EMAIL_TOKEN" VARCHAR2(64 BYTE) ,
  "TOKEN_EXPTIME" LONG 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of PWD_USER
-- ----------------------------
INSERT INTO "SCOTT"."PWD_USER" VALUES ('1', 'zhangwentian', '6a4bcd2e92a2e1ee7108f86f7ee481db', '862163687@qq.com', '862163687', ' ', '2019-05-15 17:22:27', ' ', '0:0:0:0:0:0:0:1', 'RlMk', '1', '2', '123', NULL);

-- ----------------------------
-- Primary Key structure for table PWD_LOG
-- ----------------------------
ALTER TABLE "SCOTT"."PWD_LOG" ADD CONSTRAINT "SYS_C0011057" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table PWD_LOG
-- ----------------------------
ALTER TABLE "SCOTT"."PWD_LOG" ADD CONSTRAINT "SYS_C0011121" CHECK ("URL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."PWD_LOG" ADD CONSTRAINT "SYS_C0011122" CHECK ("IP" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."PWD_LOG" ADD CONSTRAINT "SYS_C0011123" CHECK ("UA" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."PWD_LOG" ADD CONSTRAINT "SYS_C0011321" CHECK ("JSON" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."PWD_LOG" ADD CONSTRAINT "SYS_C0011322" CHECK ("TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table PWD_NOTEPAD
-- ----------------------------
ALTER TABLE "SCOTT"."PWD_NOTEPAD" ADD CONSTRAINT "SYS_C0011058" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table PWD_NOTEPAD
-- ----------------------------
ALTER TABLE "SCOTT"."PWD_NOTEPAD" ADD CONSTRAINT "SYS_C0011124" CHECK ("USERID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."PWD_NOTEPAD" ADD CONSTRAINT "SYS_C0011125" CHECK ("TITLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."PWD_NOTEPAD" ADD CONSTRAINT "SYS_C0011126" CHECK ("CONTENT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."PWD_NOTEPAD" ADD CONSTRAINT "SYS_C0011127" CHECK ("STIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."PWD_NOTEPAD" ADD CONSTRAINT "SYS_C0011128" CHECK ("TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table PWD_NOTICE
-- ----------------------------
ALTER TABLE "SCOTT"."PWD_NOTICE" ADD CONSTRAINT "SYS_C0011059" PRIMARY KEY ("ID");

-- ----------------------------
-- Primary Key structure for table PWD_PLAN
-- ----------------------------
ALTER TABLE "SCOTT"."PWD_PLAN" ADD CONSTRAINT "SYS_C0011174" PRIMARY KEY ("ID");

-- ----------------------------
-- Primary Key structure for table PWD_PWD
-- ----------------------------
ALTER TABLE "SCOTT"."PWD_PWD" ADD CONSTRAINT "SYS_C0011061" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table PWD_PWD
-- ----------------------------
ALTER TABLE "SCOTT"."PWD_PWD" ADD CONSTRAINT "SYS_C0011136" CHECK ("USERID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."PWD_PWD" ADD CONSTRAINT "SYS_C0011137" CHECK ("USERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."PWD_PWD" ADD CONSTRAINT "SYS_C0011138" CHECK ("PASS" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."PWD_PWD" ADD CONSTRAINT "SYS_C0011139" CHECK ("LASTTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."PWD_PWD" ADD CONSTRAINT "SYS_C0011140" CHECK ("TPASS" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."PWD_PWD" ADD CONSTRAINT "SYS_C0011141" CHECK ("STATUS" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."PWD_PWD" ADD CONSTRAINT "SYS_C0011142" CHECK ("TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table PWD_SET
-- ----------------------------
ALTER TABLE "SCOTT"."PWD_SET" ADD CONSTRAINT "SYS_C0011062" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table PWD_SET
-- ----------------------------
ALTER TABLE "SCOTT"."PWD_SET" ADD CONSTRAINT "SYS_C0011144" CHECK ("USERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."PWD_SET" ADD CONSTRAINT "SYS_C0011145" CHECK ("PASS" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."PWD_SET" ADD CONSTRAINT "SYS_C0011146" CHECK ("QQ" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."PWD_SET" ADD CONSTRAINT "SYS_C0011147" CHECK ("EMAIL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."PWD_SET" ADD CONSTRAINT "SYS_C0011148" CHECK ("SIGN" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table PWD_SMTP
-- ----------------------------
ALTER TABLE "SCOTT"."PWD_SMTP" ADD CONSTRAINT "SYS_C0011063" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table PWD_SMTP
-- ----------------------------
ALTER TABLE "SCOTT"."PWD_SMTP" ADD CONSTRAINT "SYS_C0011149" CHECK ("HOST" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."PWD_SMTP" ADD CONSTRAINT "SYS_C0011150" CHECK ("PORT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."PWD_SMTP" ADD CONSTRAINT "SYS_C0011151" CHECK ("USERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."PWD_SMTP" ADD CONSTRAINT "SYS_C0011152" CHECK ("PASSWORD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."PWD_SMTP" ADD CONSTRAINT "SYS_C0011153" CHECK ("SUB" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."PWD_SMTP" ADD CONSTRAINT "SYS_C0011154" CHECK ("SSL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table PWD_USER
-- ----------------------------
ALTER TABLE "SCOTT"."PWD_USER" ADD CONSTRAINT "SYS_C0011064" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table PWD_USER
-- ----------------------------
ALTER TABLE "SCOTT"."PWD_USER" ADD CONSTRAINT "SYS_C0011111" CHECK ("USERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."PWD_USER" ADD CONSTRAINT "SYS_C0011112" CHECK ("PASS" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."PWD_USER" ADD CONSTRAINT "SYS_C0011113" CHECK ("EMAIL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."PWD_USER" ADD CONSTRAINT "SYS_C0011114" CHECK ("LTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."PWD_USER" ADD CONSTRAINT "SYS_C0011115" CHECK ("LIP" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."PWD_USER" ADD CONSTRAINT "SYS_C0011116" CHECK ("TOKEN" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."PWD_USER" ADD CONSTRAINT "SYS_C0011117" CHECK ("STATUS" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."PWD_USER" ADD CONSTRAINT "SYS_C0011118" CHECK ("ERROR_NUM" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
