document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("    <meta charset=\'utf-8\'>");
document.writeln("    <meta http-equiv=\'X-UA-Compatible\' content=\'IE=edge\'>");
document.writeln("    <link rel=\'icon\' type=\'image/png\' href=\'${pageContext.request.contextPath }/assets/i/favicon.png\'>");
document.writeln("    <link rel=\'apple-touch-icon-precomposed\' href=\'${pageContext.request.contextPath }/assets/i/app-icon72x72@2x.png\'>");
document.writeln("    <meta name=\'apple-mobile-web-app-title\' content=\'Amaze UI\' />");
document.writeln("    <link rel=\'stylesheet\' href=\'${pageContext.request.contextPath }/assets/css/amazeui.min.css\' />");
document.writeln("    <link rel=\'stylesheet\' href=\'${pageContext.request.contextPath }/assets/css/fullcalendar.min.css\' />");
document.writeln("    <link rel=\'stylesheet\' href=\'${pageContext.request.contextPath }/assets/css/fullcalendar.print.css\' media=\'print\' />");
document.writeln("    <link rel=\'stylesheet\' href=\'${pageContext.request.contextPath }/assets/css/app.css\'>");
document.writeln("    <script type=\'text/javascript\' src=\'${pageContext.request.contextPath }/assets/js/jquery.min.js\'></script>");
document.writeln("    <script type=\'text/javascript\' src=\'${pageContext.request.contextPath }/assets/js/echarts.min.js\'></script>");
document.writeln("    <script type=\'text/javascript\' src=\'${pageContext.request.contextPath }/assets/layui/layui.js\'></script>");
document.writeln("    <script type=\'text/javascript\' src=\'${pageContext.request.contextPath }/assets/js/md5.js\'></script>");
document.writeln("    <link rel=\'stylesheet\' type=\'text/css\' href=\'${pageContext.request.contextPath }/assets/layui/css/layui.css\'>");
document.writeln("    ");
document.writeln("</head>");
